version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.8
  - dependency-name: css-loader
    versions:
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: css-minimizer-webpack-plugin
    versions:
    - 1.3.0
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: postcss
    versions:
    - 8.2.5
    - 8.2.6
    - 8.2.7
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
    - 8.0.17
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
  - dependency-name: sass-loader
    versions:
    - 11.0.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
  - dependency-name: commitizen
    versions:
    - 4.2.3
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
